version: '3'
services:
  web:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app
      - /app/client/node_modules
      - /app/server/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgres://admin:admin@postgres:5432/postgres?schema=aqualang"
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aqualang
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
