version: '3.2'
services:
  web:
    container_name: web
    build: .
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgres://admin:admin@postgres:5432/aqualang"
    depends_on:
      - db
  db:
    container_name: postgres
    restart: always
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aqualang
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
