name: Build Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Build
      run: npm i --also=dev && npm run build
